services:
  webdav:
    image: hacdias/webdav:latest
    ports:
      - '8080:80'
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./e2e-webdav-data:/data
    environment:
      - WEBDAV_CONFIG=/config.yml
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
