name: Lighthouse CI
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs: {}
  release:
    types: [published]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    env:
      UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
      UNSPLASH_CLIENT_ID: ${{ secrets.UNSPLASH_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - run: npm run env # Generate env.generated.ts

      - name: Build production web app
        run: npm run buildFrontend:prodWeb

      - name: Strip service worker artifacts for Lighthouse
        run: rm -f dist/browser/ngsw.json dist/browser/ngsw-worker.js dist/browser/safety-worker.js dist/browser/worker-basic.min.js

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          # Configure Lighthouse CI
          configPath: './tools/lighthouse/.lighthouserc.json'
          # Upload results to temporary storage
          uploadArtifacts: true
          temporaryPublicStorage: true
          # Run 3 times for consistency
          runs: 3
          # Configure budgets
          budgetPath: './tools/lighthouse/budget.json'
